package com.my.project.domain;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.id
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.state
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.country
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.id
     *
     * @return the value of t_city.id
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.id
     *
     * @param id the value for t_city.id
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.name
     *
     * @return the value of t_city.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.name
     *
     * @param name the value for t_city.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.state
     *
     * @return the value of t_city.state
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.state
     *
     * @param state the value for t_city.state
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.country
     *
     * @return the value of t_city.country
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.country
     *
     * @param country the value for t_city.country
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setCountry(String country) {
        this.country = country;
    }
}