package com.my.project.domain;

public class Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.city
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.address
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.zip
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    private String zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.city
     *
     * @return the value of t_hotel.city
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.city
     *
     * @param city the value for t_hotel.city
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.name
     *
     * @return the value of t_hotel.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.name
     *
     * @param name the value for t_hotel.name
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.address
     *
     * @return the value of t_hotel.address
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.address
     *
     * @param address the value for t_hotel.address
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.zip
     *
     * @return the value of t_hotel.zip
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.zip
     *
     * @param zip the value for t_hotel.zip
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip;
    }
}