package com.my.project.dao;

import com.my.project.domain.Hotel;
import com.my.project.domain.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Mon May 02 19:09:37 CST 2016
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);
}